#Data Preparation for Reporting


Here I perform a set of data preparation such as cleaning, organizing, and transforming raw data to make it suitable for generating insightful visual reports. It involves identifying and resolving data issues, such as missing values and inconsistencies, to ensure data accuracy. Additionally, data may be aggregated, integrated, and formatted appropriately to meet the specific requirements of stakeholders or users. The goal is to create a reliable and comprehensive dataset that serves as a foundation for effective data visualization, enabling better decision-making and actionable insights.

In [ ]:
import pandas as pd

In [ ]:
fix20201 = pd.read_csv("/content/drive/MyDrive/Portfolio-Projects/Speed Test/fixed_year_2020_quarter_01.csv")
fix20202 = pd.read_csv("/content/drive/MyDrive/Portfolio-Projects/Speed Test/fixed_year_2020_quarter_02.csv")
fix20203 = pd.read_csv("/content/drive/MyDrive/Portfolio-Projects/Speed Test/fixed_year_2020_quarter_03.csv")
fix20204 = pd.read_csv("/content/drive/MyDrive/Portfolio-Projects/Speed Test/fixed_year_2020_quarter_04.csv")
fix20211 = pd.read_csv("/content/drive/MyDrive/Portfolio-Projects/Speed Test/fixed_year_2021_quarter_01.csv")
fix20212 = pd.read_csv("/content/drive/MyDrive/Portfolio-Projects/Speed Test/fixed_year_2021_quarter_02.csv")
fix20213 = pd.read_csv("/content/drive/MyDrive/Portfolio-Projects/Speed Test/fixed_year_2021_quarter_03.csv")
fix20214 = pd.read_csv("/content/drive/MyDrive/Portfolio-Projects/Speed Test/fixed_year_2021_quarter_04.csv")
fix20221 = pd.read_csv("/content/drive/MyDrive/Portfolio-Projects/Speed Test/fixed_year_2022_quarter_01.csv")
fix20222 = pd.read_csv("/content/drive/MyDrive/Portfolio-Projects/Speed Test/fixed_year_2022_quarter_02.csv")
fix20223 = pd.read_csv("/content/drive/MyDrive/Portfolio-Projects/Speed Test/fixed_year_2022_quarter_03.csv")

In [ ]:
mob20201 = pd.read_csv("/content/drive/MyDrive/Portfolio-Projects/Speed Test/mobile_year_2020_quarter_01.csv")
mob20202 = pd.read_csv("/content/drive/MyDrive/Portfolio-Projects/Speed Test/mobile_year_2020_quarter_02.csv")
mob20203 = pd.read_csv("/content/drive/MyDrive/Portfolio-Projects/Speed Test/mobile_year_2020_quarter_03.csv")
mob20204 = pd.read_csv("/content/drive/MyDrive/Portfolio-Projects/Speed Test/mobile_year_2020_quarter_04.csv")
mob20211 = pd.read_csv("/content/drive/MyDrive/Portfolio-Projects/Speed Test/mobile_year_2021_quarter_01.csv")
mob20212 = pd.read_csv("/content/drive/MyDrive/Portfolio-Projects/Speed Test/mobile_year_2021_quarter_02.csv")
mob20213 = pd.read_csv("/content/drive/MyDrive/Portfolio-Projects/Speed Test/mobile_year_2021_quarter_03.csv")
mob20214 = pd.read_csv("/content/drive/MyDrive/Portfolio-Projects/Speed Test/mobile_year_2021_quarter_04.csv")
mob20221 = pd.read_csv("/content/drive/MyDrive/Portfolio-Projects/Speed Test/mobile_year_2022_quarter_01.csv")
mob20222 = pd.read_csv("/content/drive/MyDrive/Portfolio-Projects/Speed Test/mobile_year_2022_quarter_02.csv")
mob20223 = pd.read_csv("/content/drive/MyDrive/Portfolio-Projects/Speed Test/mobile_year_2022_quarter_03.csv")

## Combine Datasets

In [ ]:
fix = pd.concat([fix20201, fix20202, fix20203, fix20204, fix20211, fix20212, fix20213, fix20214, fix20221, fix20222, fix20223], axis=0).reset_index()
mobile= pd.concat([mob20201, mob20202, mob20203, mob20204, mob20211, mob20212, mob20213, mob20214, mob20221, mob20222, mob20223], axis=0).reset_index()

In [ ]:
fix = fix.drop("index", axis=1)
mobile = mobile.drop("index", axis=1)

## Set Flag for Dashboard Filtering

In [ ]:
fix['Flag']='fixed'
mobile['Flag']='mobile'

## Get Last Quarter Value for Each Country for Comparison

In [ ]:
fix.head()

,Name,Number of Records,Devices,Tests,Avg. Avg U Kbps,Avg. Avg D Kbps,Avg Lat Ms,Avg. Pop2005,Rank Upload,Rank Download,...,Quarter,Flag,LQ_Avg_Up,LQ_Avg_DL,LQ_Latency,LQ_Devices,LQ_Tests,LQ_Rank_Up,LQ_Rank_DL,LQ_Rank_Lat
0,Afghanistan,989,"3,776","15,046","3,984","3,564",85,"25,067,407",193,226,...,1,fixed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Åland Islands,252,485,"1,068","52,179","64,138",12,0,18,34,...,1,fixed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Albania,"8,275","45,779","174,707","10,008","13,911",29,"3,153,731",107,140,...,1,fixed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Algeria,"11,913","39,923","170,080","1,368","3,492",61,"32,854,159",230,227,...,1,fixed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,American Samoa,81,209,691,"6,948","20,147",185,"64,051",138,104,...,1,fixed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Step 1: Sort the DataFrame by Country, Year, and Quarter
fix.sort_values(['Name', 'Year', 'Quarter'], inplace=True)

In [ ]:
fix['LQ_Avg_Up'] = fix.groupby('Name')['Avg. Avg U Kbps'].shift()
fix['LQ_Avg_DL'] = fix.groupby('Name')['Avg. Avg D Kbps'].shift()
fix['LQ_Latency'] = fix.groupby('Name')['Avg Lat Ms'].shift()
fix['LQ_Devices'] = fix.groupby('Name')['Devices'].shift()
fix['LQ_Tests'] = fix.groupby('Name')['Tests'].shift()
fix['LQ_Rank_Up'] = fix.groupby('Name')['Rank Upload'].shift()
fix['LQ_Rank_DL'] = fix.groupby('Name')['Rank Download'].shift()
fix['LQ_Rank_Lat'] = fix.groupby('Name')['Rank Latency'].shift()

In [ ]:
fix.head(20)

,Name,Number of Records,Devices,Tests,Avg. Avg U Kbps,Avg. Avg D Kbps,Avg Lat Ms,Avg. Pop2005,Rank Upload,Rank Download,...,Quarter,Flag,LQ_Avg_Up,LQ_Avg_DL,LQ_Latency,LQ_Devices,LQ_Tests,LQ_Rank_Up,LQ_Rank_DL,LQ_Rank_Lat
0,Afghanistan,989,"3,776","15,046","3,984","3,564",85,"25,067,407",193,226,...,1,fixed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
234,Afghanistan,"1,080","3,950","20,829","3,435","3,223",94,"25,067,407",203,226,...,2,fixed,"3,984","3,564",85.0,"3,776","15,046",193.0,226.0,41.0
469,Afghanistan,988,"3,418","13,544","4,181","3,672",87,"25,067,407",197,227,...,3,fixed,"3,435","3,223",94.0,"3,950","20,829",203.0,226.0,36.0
703,Afghanistan,874,"2,573","9,475","4,364","3,687",71,"25,067,407",202,227,...,4,fixed,"4,181","3,672",87.0,"3,418","13,544",197.0,227.0,29.0
939,Afghanistan,"1,074","3,491","14,643","4,412","3,920",65,"25,067,407",207,229,...,1,fixed,"4,364","3,687",71.0,"2,573","9,475",202.0,227.0,36.0
1174,Afghanistan,"1,027","3,279","12,185","4,418","5,125",60,"25,067,407",207,230,...,2,fixed,"4,412","3,920",65.0,"3,491","14,643",207.0,229.0,41.0
1410,Afghanistan,897,"2,312","9,003","3,983","4,823",70,"25,067,407",217,231,...,3,fixed,"4,418","5,125",60.0,"3,279","12,185",207.0,230.0,41.0
1646,Afghanistan,800,"1,873","8,973","4,174","5,217",65,"25,067,407",215,228,...,4,fixed,"3,983","4,823",70.0,"2,312","9,003",217.0,231.0,33.0
1916,Afghanistan,844,"1,925","9,095","3,078","3,599",73,"25,067,407",223,230,...,1,fixed,"4,174","5,217",65.0,"1,873","8,973",215.0,228.0,36.0
2120,Afghanistan,802,"1,722","8,108","3,879","4,012",61,"25,067,407",224,231,...,2,fixed,"3,078","3,599",73.0,"1,925","9,095",223.0,230.0,34.0
2409,Afghanistan,775,"1,792","7,968","3,833","3,795",58,"25,067,407",222,234,...,3,fixed,"3,879","4,012",61.0,"1,722","8,108",224.0,231.0,43.0
2,Albania,"8,275","45,779","174,707","10,008","13,911",29,"3,153,731",107,140,...,1,fixed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
236,Albania,"9,679","49,508","201,307","10,814","14,778",26,"3,153,731",105,141,...,2,fixed,"10,008","13,911",29.0,"45,779","174,707",107.0,140.0,155.0
471,Albania,"8,274","42,388","132,000","12,401","16,818",21,"3,153,731",98,132,...,3,fixed,"10,814","14,778",26.0,"49,508","201,307",105.0,141.0,160.0
705,Albania,"7,531","37,113","130,957","14,067","19,184",22,"3,153,731",97,125,...,4,fixed,"12,401","16,818",21.0,"42,388","132,000",98.0,132.0,171.0
941,Albania,"8,048","41,138","153,784","15,335","21,176",23,"3,153,731",101,126,...,1,fixed,"14,067","19,184",22.0,"37,113","130,957",97.0,125.0,161.0
1176,Albania,"7,010","34,187","107,265","16,685","24,843",20,"3,153,731",98,125,...,2,fixed,"15,335","21,176",23.0,"41,138","153,784",101.0,126.0,156.0
1412,Albania,"7,215","38,905","104,752","17,354","25,803",20,"3,153,731",100,127,...,3,fixed,"16,685","24,843",20.0,"34,187","107,265",98.0,125.0,162.0
1648,Albania,"6,369","30,635","97,645","18,783","28,415",17,"3,153,731",101,128,...,4,fixed,"17,354","25,803",20.0,"38,905","104,752",100.0,127.0,159.0
2060,Albania,"6,319","29,346","100,033","20,850","31,146",17,"3,153,731",105,123,...,1,fixed,"18,783","28,415",17.0,"30,635","97,645",101.0,128.0,176.0

In [ ]:
fix = fix.sort_index()
fix.head()

,Name,Number of Records,Devices,Tests,Avg. Avg U Kbps,Avg. Avg D Kbps,Avg Lat Ms,Avg. Pop2005,Rank Upload,Rank Download,...,Quarter,Flag,LQ_Avg_Up,LQ_Avg_DL,LQ_Latency,LQ_Devices,LQ_Tests,LQ_Rank_Up,LQ_Rank_DL,LQ_Rank_Lat
0,Afghanistan,989,"3,776","15,046","3,984","3,564",85,"25,067,407",193,226,...,1,fixed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Åland Islands,252,485,"1,068","52,179","64,138",12,0,18,34,...,1,fixed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Albania,"8,275","45,779","174,707","10,008","13,911",29,"3,153,731",107,140,...,1,fixed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Algeria,"11,913","39,923","170,080","1,368","3,492",61,"32,854,159",230,227,...,1,fixed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,American Samoa,81,209,691,"6,948","20,147",185,"64,051",138,104,...,1,fixed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
mobile.head()

,Name,Number of Records,Devices,Tests,Avg. Avg U Kbps,Avg. Avg D Kbps,Avg Lat Ms,Avg. Pop2005,Rank Upload,Rank Download,Rank Latency,Year,Quarter,Flag
0,Afghanistan,789,"1,241","3,541","3,099","6,387",70,"25,067,407",220,220,32,2020,1,mobile
1,Albania,"1,626","4,513","7,228","11,414","40,238",26,"3,153,731",75,42,197,2020,1,mobile
2,Algeria,"14,174","48,699","124,160","6,150","7,724",65,"32,854,159",197,213,35,2020,1,mobile
3,American Samoa,23,33,63,"8,488","22,792",62,"64,051",156,111,38,2020,1,mobile
4,Andorra,45,83,110,"18,160","72,764",39,"73,483",9,6,112,2020,1,mobile

In [ ]:
# Step 1: Sort the DataFrame by Country, Year, and Quarter
mobile.sort_values(['Name', 'Year', 'Quarter'], inplace=True)

In [ ]:
mobile['LQ_Avg_Up'] = mobile.groupby('Name')['Avg. Avg U Kbps'].shift()
mobile['LQ_Avg_DL'] = mobile.groupby('Name')['Avg. Avg D Kbps'].shift()
mobile['LQ_Latency'] = mobile.groupby('Name')['Avg Lat Ms'].shift()
mobile['LQ_Devices'] = mobile.groupby('Name')['Devices'].shift()
mobile['LQ_Tests'] = mobile.groupby('Name')['Tests'].shift()
mobile['LQ_Rank_Up'] = mobile.groupby('Name')['Rank Upload'].shift()
mobile['LQ_Rank_DL'] = mobile.groupby('Name')['Rank Download'].shift()
mobile['LQ_Rank_Lat'] = mobile.groupby('Name')['Rank Latency'].shift()

In [ ]:
mobile.head(20)

,Name,Number of Records,Devices,Tests,Avg. Avg U Kbps,Avg. Avg D Kbps,Avg Lat Ms,Avg. Pop2005,Rank Upload,Rank Download,...,Quarter,Flag,LQ_Avg_Up,LQ_Avg_DL,LQ_Latency,LQ_Devices,LQ_Tests,LQ_Rank_Up,LQ_Rank_DL,LQ_Rank_Lat
0,Afghanistan,789,"1,241","3,541","3,099","6,387",70,"25,067,407",220,220,...,1,mobile,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
224,Afghanistan,665,960,"2,452","2,832","6,292",75,"25,067,407",219,217,...,2,mobile,"3,099","6,387",70,"1,241","3,541",220.0,220.0,32.0
448,Afghanistan,664,"1,002","2,455","3,255","6,419",70,"25,067,407",219,221,...,3,mobile,"2,832","6,292",75,960,"2,452",219.0,217.0,27.0
672,Afghanistan,659,"1,039","2,418","2,861","5,920",78,"25,067,407",220,223,...,4,mobile,"3,255","6,419",70,"1,002","2,455",219.0,221.0,26.0
898,Afghanistan,842,"1,437","2,954","2,585","5,369",78,"25,067,407",219,220,...,1,mobile,"2,861","5,920",78,"1,039","2,418",220.0,223.0,26.0
1122,Afghanistan,790,"1,280","2,438","2,374","5,908",78,"25,067,407",221,221,...,2,mobile,"2,585","5,369",78,"1,437","2,954",219.0,220.0,21.0
1348,Afghanistan,593,844,"1,802","3,066","6,867",77,"25,067,407",219,219,...,3,mobile,"2,374","5,908",78,"1,280","2,438",221.0,221.0,26.0
1572,Afghanistan,774,"1,103","2,715","3,447","7,919",62,"25,067,407",219,220,...,4,mobile,"3,066","6,867",77,844,"1,802",219.0,219.0,22.0
1796,Afghanistan,842,"1,257","3,134","3,158","7,441",60,"25,067,407",221,222,...,1,mobile,"3,447","7,919",62,"1,103","2,715",219.0,220.0,28.0
2021,Afghanistan,700,938,"2,480","3,442","6,949",56,"25,067,407",223,224,...,2,mobile,"3,158","7,441",60,"1,257","3,134",221.0,222.0,34.0
2315,Afghanistan,756,"1,060","2,504","4,257","7,313",52,"25,067,407",224,225,...,3,mobile,"3,442","6,949",56,938,"2,480",223.0,224.0,54.0
1,Albania,"1,626","4,513","7,228","11,414","40,238",26,"3,153,731",75,42,...,1,mobile,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
225,Albania,"1,724","4,314","6,649","11,509","44,686",25,"3,153,731",82,37,...,2,mobile,"11,414","40,238",26,"4,513","7,228",75.0,42.0,197.0
449,Albania,"1,927","5,341","8,168","12,528","42,206",28,"3,153,731",69,44,...,3,mobile,"11,509","44,686",25,"4,314","6,649",82.0,37.0,192.0
673,Albania,"2,253","6,723","11,573","13,627","45,171",24,"3,153,731",53,45,...,4,mobile,"12,528","42,206",28,"5,341","8,168",69.0,44.0,177.0
899,Albania,"2,249","6,493","10,782","12,177","38,350",25,"3,153,731",76,60,...,1,mobile,"13,627","45,171",24,"6,723","11,573",53.0,45.0,197.0
1123,Albania,"1,873","4,737","7,478","12,662","43,840",26,"3,153,731",69,61,...,2,mobile,"12,177","38,350",25,"6,493","10,782",76.0,60.0,179.0
1349,Albania,"2,194","5,927","9,202","12,371","41,781",30,"3,153,731",79,66,...,3,mobile,"12,662","43,840",26,"4,737","7,478",69.0,61.0,179.0
1573,Albania,"1,928","5,220","9,329","12,422","44,850",26,"3,153,731",102,71,...,4,mobile,"12,371","41,781",30,"5,927","9,202",79.0,66.0,148.0
1797,Albania,"1,832","4,753","8,537","13,448","43,269",26,"3,153,731",80,74,...,1,mobile,"12,422","44,850",26,"5,220","9,329",102.0,71.0,181.0

In [ ]:
mobile = mobile.sort_index()
mobile.tail()

,Name,Number of Records,Devices,Tests,Avg. Avg U Kbps,Avg. Avg D Kbps,Avg Lat Ms,Avg. Pop2005,Rank Upload,Rank Download,...,Quarter,Flag,LQ_Avg_Up,LQ_Avg_DL,LQ_Latency,LQ_Devices,LQ_Tests,LQ_Rank_Up,LQ_Rank_DL,LQ_Rank_Lat
2482,Maldives,27,259,423,"17,983","91,925",21,"295,297",29,31,...,3,mobile,"18,336","101,415",35,245,445,31.0,24.0,146.0
2483,Brunei Darussalam,586,"1,468","2,632","33,814","91,191",21,"373,831",1,35,...,3,mobile,"31,847","96,535",19,"1,575","3,631",1.0,28.0,233.0
2484,Hong Kong,"1,412","36,027","98,055","15,450","83,416",21,"7,057,418",51,39,...,3,mobile,"15,443","83,415",20,"39,249","98,477",49.0,37.0,231.0
2485,Guinea-Bissau,46,89,485,"22,842","91,219",20,"1,596,929",14,34,...,3,mobile,"16,034","24,619",37,74,227,43.0,153.0,132.0
2486,Saint Pierre and Miquelon,9,10,14,"19,145","105,807",19,"6,346",22,19,...,3,mobile,"23,613","129,977",44,14,22,14.0,12.0,97.0

## Combine Mobile and Fixed Data

In [ ]:
data = pd.concat([fix, mobile], axis=0).reset_index()

In [ ]:
data = data.drop("index", axis=1)
data

,Name,Number of Records,Devices,Tests,Avg. Avg U Kbps,Avg. Avg D Kbps,Avg Lat Ms,Avg. Pop2005,Rank Upload,Rank Download,...,Quarter,Flag,LQ_Avg_Up,LQ_Avg_DL,LQ_Latency,LQ_Devices,LQ_Tests,LQ_Rank_Up,LQ_Rank_DL,LQ_Rank_Lat
0,Afghanistan,989,"3,776","15,046","3,984","3,564",85,"25,067,407",193,226,...,1,fixed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Åland Islands,252,485,"1,068","52,179","64,138",12,0,18,34,...,1,fixed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Albania,"8,275","45,779","174,707","10,008","13,911",29,"3,153,731",107,140,...,1,fixed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Algeria,"11,913","39,923","170,080","1,368","3,492",61,"32,854,159",230,227,...,1,fixed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,American Samoa,81,209,691,"6,948","20,147",185,"64,051",138,104,...,1,fixed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5079,Maldives,27,259,423,"17,983","91,925",21,"295,297",29,31,...,3,mobile,"18,336","101,415",35,245,445,31.0,24.0,146.0
5080,Brunei Darussalam,586,"1,468","2,632","33,814","91,191",21,"373,831",1,35,...,3,mobile,"31,847","96,535",19,"1,575","3,631",1.0,28.0,233.0
5081,Hong Kong,"1,412","36,027","98,055","15,450","83,416",21,"7,057,418",51,39,...,3,mobile,"15,443","83,415",20,"39,249","98,477",49.0,37.0,231.0
5082,Guinea-Bissau,46,89,485,"22,842","91,219",20,"1,596,929",14,34,...,3,mobile,"16,034","24,619",37,74,227,43.0,153.0,132.0
5083,Saint Pierre and Miquelon,9,10,14,"19,145","105,807",19,"6,346",22,19,...,3,mobile,"23,613","129,977",44,14,22,14.0,12.0,97.0

## Concat Year and Quarter for Filtering

In [ ]:
data['YearQuarter'] = data['Year'].astype(str) + 'Q' + data['Quarter'].astype(str)

In [ ]:
data

,Name,Number of Records,Devices,Tests,Avg. Avg U Kbps,Avg. Avg D Kbps,Avg Lat Ms,Avg. Pop2005,Rank Upload,Rank Download,...,Flag,LQ_Avg_Up,LQ_Avg_DL,LQ_Latency,LQ_Devices,LQ_Tests,LQ_Rank_Up,LQ_Rank_DL,LQ_Rank_Lat,YearQuarter
0,Afghanistan,989,"3,776","15,046","3,984","3,564",85,"25,067,407",193,226,...,fixed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020Q1
1,Åland Islands,252,485,"1,068","52,179","64,138",12,0,18,34,...,fixed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020Q1
2,Albania,"8,275","45,779","174,707","10,008","13,911",29,"3,153,731",107,140,...,fixed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020Q1
3,Algeria,"11,913","39,923","170,080","1,368","3,492",61,"32,854,159",230,227,...,fixed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020Q1
4,American Samoa,81,209,691,"6,948","20,147",185,"64,051",138,104,...,fixed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020Q1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5079,Maldives,27,259,423,"17,983","91,925",21,"295,297",29,31,...,mobile,"18,336","101,415",35,245,445,31.0,24.0,146.0,2022Q3
5080,Brunei Darussalam,586,"1,468","2,632","33,814","91,191",21,"373,831",1,35,...,mobile,"31,847","96,535",19,"1,575","3,631",1.0,28.0,233.0,2022Q3
5081,Hong Kong,"1,412","36,027","98,055","15,450","83,416",21,"7,057,418",51,39,...,mobile,"15,443","83,415",20,"39,249","98,477",49.0,37.0,231.0,2022Q3
5082,Guinea-Bissau,46,89,485,"22,842","91,219",20,"1,596,929",14,34,...,mobile,"16,034","24,619",37,74,227,43.0,153.0,132.0,2022Q3
5083,Saint Pierre and Miquelon,9,10,14,"19,145","105,807",19,"6,346",22,19,...,mobile,"23,613","129,977",44,14,22,14.0,12.0,97.0,2022Q3

In [ ]:
data.to_csv("/content/drive/MyDrive/Portfolio-Projects/Speed Test/SpeedTest_Cleaned.csv", index=False)